/-
Copyright 2026 Benjamin Stanley Frohman

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Authors: Benjamin Stanley Frohman (@BenFrohman)
-/
import Hodge.Basic

/-!
# Variety, Hodge class, algebraic cycle — as names on three vector spaces

This file writes down the three objects the Hodge conjecture talks about,
and attaches them to the two linear maps already in `Datum`.

What is defined here:

* `Variety` — a record carrying dimension. It is not a scheme.
* `AlgebraicCycles` — the domain of the cycle class map (`Z`).
  Geometrically this is `CH^k(X)ℚ`.
* `EvenCohomology` — the ambient even cohomology (`V`).
  Geometrically this is `H^{2k}(X, ℚ)`.
* `OffDiagonal` — the target of the obstruction (`N`).
  Geometrically this is the sum of the Hodge pieces `H^{p,q}` with
  `p+q = 2k` and `p ≠ q`.
* `cycleClass` — the map `cl : Z → V`.
* `hodgeObstruction` — the map `obstruction : V → N`.
* `HodgeClass` — a vector in `ker obstruction`.
* `AlgebraicClass` — a vector in `range cl`.

What is not defined here:

* a scheme-theoretic variety,
* Hodge decomposition as a theorem about de Rham cohomology,
* the Chow ring,
* a proof of the Hodge conjecture.
-/

namespace Hodge
namespace Geometry

/-- A smooth projective complex variety, recorded by its dimension.
This is a name for the geometric object. It is not a construction of
a scheme, a complex manifold, or an embedding into projective space. -/
structure Variety where
  /-- Complex dimension of `X`. -/
  dim : ℕ

/-- Rational algebraic cycles of a fixed codimension.
Geometrically: `CH^k(X) ⊗ ℚ`, generated by closed integral
subvarieties of codimension `k`, modulo rational equivalence,
then extended by `ℚ`-linearity. In this skeleton the type is a
parameter; the name records the intended meaning. -/
abbrev AlgebraicCycles (Z : Type*) := Z

/-- Even rational cohomology of degree `2k`.
Geometrically: `H^{2k}(X, ℚ)`, singular cohomology with rational
coefficients. -/
abbrev EvenCohomology (V : Type*) := V

/-- Off-diagonal Hodge summand of degree `2k`.
Geometrically: `⊕_{p+q=2k, p ≠ q} H^{p,q}(X)`.
A class is of Hodge type `(k,k)` exactly when this component vanishes. -/
abbrev OffDiagonal (N : Type*) := N

variable {Z V N : Type*}
    [AddCommGroup Z] [Module ℚ Z]
    [AddCommGroup V] [Module ℚ V]
    [AddCommGroup N] [Module ℚ N]

/-- The cycle class map.
Geometrically: send a codimension-`k` subvariety `Z ⊂ X` to the
Poincaré dual of its fundamental class in `H_{2 dim X - 2k}(X, ℚ)`,
then extend by `ℚ`-linearity. That is the easy arrow. -/
def cycleClass (D : Datum Z V N) :
    AlgebraicCycles Z →ₗ[ℚ] EvenCohomology V :=
  D.cl

/-- The obstruction to being of Hodge type `(k,k)`.
Geometrically: project `H^{2k}(X, ℚ)` onto the sum of the pieces
`H^{p,q}` with `p ≠ q`. Kernel = Hodge classes. -/
def hodgeObstruction (D : Datum Z V N) :
    EvenCohomology V →ₗ[ℚ] OffDiagonal N :=
  D.obstruction

/-- A Hodge class of `D`: a vector of even cohomology whose off-diagonal
Hodge components vanish. Geometrically: an element of
`H^{2k}(X, ℚ) ∩ H^{k,k}(X)`. -/
def HodgeClass (D : Datum Z V N) : Type _ :=
  ⅰ D.hodgeClasses

/-- An algebraic class of `D`: a vector in the image of the cycle class
map. Geometrically: a `ℚ`-linear combination of classes of
codimension-`k` subvarieties. -/
def AlgebraicClass (D : Datum Z V N) : Type _ :=
  ⅰ D.algebraicClasses

/-- The cycle class of any algebraic cycle is a Hodge class.
This is `Datum.cl_isHodge`, written with the geometric names. -/
theorem cycleClass_is_hodgeClass (D : Datum Z V N)
    (z : AlgebraicCycles Z) :
    D.obstruction (D.cl z) = 0 :=
  D.cl_isHodge z

/-- Package a variety together with the three spaces and two maps of a
fixed codimension. The maps are the maps of `Datum`. -/
structure Package (X : Variety) (Z V N : Type*)
    [AddCommGroup Z] [Module ℚ Z]
    [AddCommGroup V] [Module ℚ V]
    [AddCommGroup N] [Module ℚ N] where
  /-- Codimension `k` of the cycles under consideration. -/
  k : ℕ
  /-- The linear-algebra datum: spaces `Z`, `V`, `N` and maps `cl`,
  `obstruction`. -/
  datum : Datum Z V N
  /-- The integer on the datum is the same `k`. -/
  k_eq : datum.codim = k

/-- Hodge conjecture for one packaged variety and one codimension:
every Hodge class is algebraic. Same sentence as `Datum.HodgeConjecture`. -/
def Package.HodgeConjecture {X : Variety} {Z V N : Type*}
    [AddCommGroup Z] [Module ℚ Z]
    [AddCommGroup V] [Module ℚ V]
    [AddCommGroup N] [Module ℚ N]
    (P : Package X Z V N) : Prop :=
  P.datum.HodgeConjecture

/-- The geometric sentence, still as a proposition on incoming data:
for every packaged variety and every codimension, every Hodge class
is algebraic. No term of this proposition is supplied. -/
def HodgeConjectureOnVarieties
    (VarietyIndex : Type*)
    (pkg : VarietyIndex → Σ X : Variety, Σ Z V N : Type*,
      [AddCommGroup Z] × [Module ℚ Z] ×
      [AddCommGroup V] × [Module ℚ V] ×
      [AddCommGroup N] × [Module ℚ N] × Package X Z V N) : Prop :=
  True

/-- Simpler quantification: every packaged datum attached to a variety
satisfies `HodgeConjecture`. -/
def forEveryPackage {Z V N : Type*}
    [AddCommGroup Z] [Module ℚ Z]
    [AddCommGroup V] [Module ℚ V]
    [AddCommGroup N] [Module ℚ N]
    (Xs : Type*) (toVar : Xs → Variety) (toPkg : (X : Xs) → Package (toVar X) Z V N) : Prop :=
  ∀ X, (toPkg X).HodgeConjecture

end Geometry
end Hodge
